import React from 'react';
import { ScrollView, Text, StyleSheet, SafeAreaView, StatusBar, Platform } from 'react-native';

export default function Privacy() {
  return (
    <SafeAreaView style={styles.safeArea}>
      <ScrollView contentContainerStyle={styles.container}>
        <Text style={styles.title}>Joyn OS — Privacy Policy (Draft)</Text>
        <Text style={styles.updated}>Last updated: August 8, 2025</Text>

        <Text style={styles.h2}>1) Scope and who we are</Text>
        <Text style={styles.p}>This Privacy Policy explains how Joyn OS, Inc. ("Joyn OS," "we," "us") collects, uses, shares, and protects personal information when you use our mobile apps, websites, and related Services.</Text>

        <Text style={styles.h2}>2) What we collect</Text>
        <Text style={styles.p}>We collect information in three main ways: (A) you provide it; (B) it’s generated by your use of the Services; or (C) we get it from third‑party partners.</Text>

        <Text style={styles.h3}>A. Information you provide</Text>
        <Text style={styles.p}>Account details: display name, age confirmation (18+), contact details (e.g., email/phone), profile photos.{"\n\n"}
Verification (optional/feature‑gated): selfie, liveness checks, and-if you choose-government‑ID scans via verification vendors. Verification status may be shown to other users.{"\n\n"}
Preferences & quiz responses: answers to the short “vibe/energy” quiz and activity/budget preferences.{"\n\n"}
Communications & content: lobby chats, plan titles/pitches, feedback, and support requests.</Text>

        <Text style={styles.h3}>B. Information from your use of the Services</Text>
        <Text style={styles.p}>Live intent & availability: toggles such as “Tonight/This Week,” preferred time windows, and plan choices.{"\n\n"}
Location data: precise GPS (if you grant permission) for nearby options and check‑ins; coarse location (e.g., city/area or blurred radius) if you choose privacy‑preserving modes. Precise location is purged after 24 hours except limited security logs.{"\n\n"}
Reliability & safety signals: commitment/no‑show patterns and abuse reports used to maintain a safer environment; non‑numeric badges (e.g., “Reliable”) may be visible to others.{"\n\n"}
“Explain my match” logs: high‑level factors shown in the panel are logged for 30 days to support transparency.{"\n\n"}
Device & usage data: app version, device identifiers, push tokens, diagnostic events (e.g., OpenTelemetry traces) and performance metrics used to keep the Services reliable and secure.{"\n\n"}
Calendar & notifications: if you add plans to your calendar, we provide an ICS link; we do not read your calendar content. We send pushes only when your action is required, per our “earned attention” principle.</Text>

        <Text style={styles.h3}>C. Information from partners</Text>
        <Text style={styles.p}>Reservations & venues: metadata and links from mapping, dining, and ticketing providers (e.g., Google Places/Maps, Yelp, OpenTable, Resy, SevenRooms, Ticketmaster).{"\n\n"}
Payments: limited billing details from our payment processor (currently Stripe). We do not receive or store full card numbers.</Text>

        <Text style={styles.h2}>3) How we use information</Text>
        <Text style={styles.p}>We use information to: provide core flows (matching, lobbies, plan generation, reservations, check‑ins); operate reliability and safety features, block/report workflows, and fraud prevention; power the “Explain my match” panel and fulfill transparency commitments; process payments, show accurate prices, and handle support; improve the Services, including AI ranking/re‑ranking and performance; communicate important updates and reminders (e.g., commitments, time windows); comply with law and enforce our Terms.</Text>

        <Text style={styles.h2}>4) Automated decision‑making & transparency</Text>
        <Text style={styles.p}>Our matching engine weighs complementary energy/archetypes, interests, timing/availability, credibility signals, location radius, and venue preferences to suggest plans and people. We expose high‑level reasons in the “Explain my match” panel and log the factors for 30 days to support user understanding. You can ask support to review a decision you believe is inaccurate or unfair, and you can adjust your preferences at any time.</Text>

        <Text style={styles.h2}>5) Legal bases for processing (EEA/UK users)</Text>
        <Text style={styles.p}>Where applicable law requires a legal basis, we rely on: contract (to provide the Services), legitimate interests (safety, fraud prevention, service improvement, transparency features), consent (e.g., precise location, marketing), and legal obligation (e.g., responding to lawful requests).</Text>

        <Text style={styles.h2}>6) Sharing your information</Text>
        <Text style={styles.p}>We share information with: Service providers that help us run the Services (e.g., hosting, analytics, verification, trust & safety vendors, OpenTelemetry/observability, customer support). Payments (currently Stripe) to process transactions; we receive tokens and limited billing metadata. Mapping, reservation, and ticketing partners to surface plan options and route bookings (directory deep links or live inventory where available). Other users when you join lobbies, commit to plans, or check in (e.g., your display name, avatar, high‑level reliability badge, coarse radius). Law enforcement or regulators when required by law or to protect safety. Corporate transactions (merger, financing, acquisition) subject to appropriate safeguards.{"\n\n"}We do not sell your personal data. We may use de‑identified or aggregated data for analytics, product decisions, and market insights.</Text>

        <Text style={styles.h2}>7) Your choices and controls</Text>
        <Text style={styles.p}>Location controls: You can disable precise location or use a blurred radius. Some features may not work without location.{"\n\n"}Explainability: Use “Why this match?” to see high‑level factors; contact support if you think something’s off.{"\n\n"}Notifications: Control push notifications in system settings and in‑app.{"\n\n"}Access, portability, correction, deletion: Request a copy of your data, ask us to correct inaccuracies, or delete your account. We’ll honor requests as required by law and will explain any denials or exemptions that apply.</Text>

        <Text style={styles.h2}>8) Data retention</Text>
        <Text style={styles.p}>Precise location: purged within 24 hours (with limited security/abuse exceptions).{"\n\n"}Explain‑my‑match factor logs: 30 days.{"\n\n"}Account, chat, and plan metadata: retained while your account is active and then deleted or anonymized within a commercially reasonable period (default target: within 12 months after account deletion, unless we must keep it longer for legal/security reasons).{"\n\n"}Payment records: as required for tax, accounting, and fraud prevention.</Text>

        <Text style={styles.h2}>9) Security</Text>
        <Text style={styles.p}>We use administrative, technical, and physical safeguards, including encryption in transit, network segmentation, access controls, and monitoring. Our controls are aligned to ISO 27001 practices, but certification status may vary over time. No system is 100% secure.</Text>

        <Text style={styles.h2}>10) Children’s privacy</Text>
        <Text style={styles.p}>Joyn OS is 18+ only. We do not knowingly collect data from minors and will delete such data if discovered.</Text>

        <Text style={styles.h2}>11) Region‑specific disclosures</Text>
        <Text style={styles.p}>California (CPRA): We do not “sell” personal information as defined by CPRA. You have rights to know, delete, correct, and opt out of sharing for cross‑context behavioral advertising (we do not run targeted ads in the MVP).{"\n\n"}EEA/UK: You have rights to access, rectify, delete, restrict, object, and port your data, and to lodge a complaint with your data protection authority.</Text>

        <Text style={styles.h2}>12) International transfers</Text>
        <Text style={styles.p}>If we transfer your data internationally, we use lawful transfer mechanisms (e.g., standard contractual clauses) and implement appropriate safeguards.</Text>

        <Text style={styles.h2}>13) Changes to this Policy</Text>
        <Text style={styles.p}>We may update this Policy to reflect changes in our Services or laws. We will notify you in‑app or by email before material changes take effect.</Text>

        <Text style={styles.h2}>14) Contact us</Text>
        <Text style={styles.p}>Data controller: Joyn OS, Inc.{"\n"}Email: [insert privacy email]{"\n"}Mailing address: [insert address]</Text>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#000',
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  container: {
    padding: 24,
  },
  title: {
    fontSize: 22,
    color: '#fff',
    fontWeight: '700',
    marginBottom: 4,
  },
  updated: {
    color: '#aaa',
    marginBottom: 16,
  },
  h2: {
    fontSize: 16,
    color: '#fff',
    fontWeight: '700',
    marginTop: 16,
    marginBottom: 8,
  },
  h3: {
    fontSize: 15,
    color: '#fff',
    fontWeight: '700',
    marginTop: 12,
    marginBottom: 6,
  },
  p: {
    fontSize: 14,
    color: '#ddd',
    lineHeight: 20,
  },
});