export const INTERESTS = [
    '🎵 Jazz Music',
    '🎨 Art Galleries',
    '🍷 Wine Tasting',
    '📚 Book Clubs',
    '🥾 Hiking',
    '🍳 Cooking',
    '🎭 Theater',
    '📸 Photography',
    '🏃‍♂️ Running',
    '🎮 Gaming',
    '🌱 Gardening',
    '✈️ Travel',
    '🧘‍♀️ Meditation',
    '🍕 Food Tours',
    '🎪 Comedy Shows',
    '🏛️ Museums',
    '🎸 Live Music',
    '🏖️ Beach Days',
    '🎤 Karaoke',
    '🎲 Games',
] as const;